/**
 * Escudos dos clubes e logo do campeonato (PNGs empacotados pelo Metro).
 * Organizados por divisão em `escudos/<serie>/club_<slug>.png` e mapeados pelo id
 * do clube (ver src/data/seed/clubes/). Arquivos leves (128px, transparentes) —
 * o suficiente para os tamanhos de exibição (até ~50px), sem peso morto no bundle.
 */

import type {ImageSourcePropType} from 'react-native';

export const ESCUDOS: Record<string, ImageSourcePropType> = {
  // Série A
  club_bahia: require('./serie-a/club_bahia.png'),
  club_vitoria: require('./serie-a/club_vitoria.png'),
  club_fluminense: require('./serie-a/club_fluminense.png'),
  club_corinthians: require('./serie-a/club_corinthians.png'),
  club_vasco: require('./serie-a/club_vasco.png'),
  club_sao_paulo: require('./serie-a/club_sao_paulo.png'),
  club_flamengo: require('./serie-a/club_flamengo.png'),
  club_botafogo: require('./serie-a/club_botafogo.png'),
  club_gremio: require('./serie-a/club_gremio.png'),
  club_cruzeiro: require('./serie-a/club_cruzeiro.png'),
  club_internacional: require('./serie-a/club_internacional.png'),
  club_palmeiras: require('./serie-a/club_palmeiras.png'),
  club_atletico_mg: require('./serie-a/club_atletico_mg.png'),
  club_santos: require('./serie-a/club_santos.png'),
  club_bragantino: require('./serie-a/club_bragantino.png'),
  club_mirassol: require('./serie-a/club_mirassol.png'),
  club_athletico_pr: require('./serie-a/club_athletico_pr.png'),
  club_chapecoense: require('./serie-a/club_chapecoense.png'),
  club_coritiba: require('./serie-a/club_coritiba.png'),
  club_remo: require('./serie-a/club_remo.png'),
  // Série B
  club_fortaleza: require('./serie-b/club_fortaleza.png'),
  club_sport: require('./serie-b/club_sport.png'),
  club_ceara: require('./serie-b/club_ceara.png'),
  club_juventude: require('./serie-b/club_juventude.png'),
  club_novorizontino: require('./serie-b/club_novorizontino.png'),
  club_goias: require('./serie-b/club_goias.png'),
  club_criciuma: require('./serie-b/club_criciuma.png'),
  club_crb: require('./serie-b/club_crb.png'),
  club_athletic: require('./serie-b/club_athletic.png'),
  club_cuiaba: require('./serie-b/club_cuiaba.png'),
  club_avai: require('./serie-b/club_avai.png'),
  club_vila_nova: require('./serie-b/club_vila_nova.png'),
  club_america_mg: require('./serie-b/club_america_mg.png'),
  club_operario: require('./serie-b/club_operario.png'),
  club_atletico_go: require('./serie-b/club_atletico_go.png'),
  club_sao_bernardo: require('./serie-b/club_sao_bernardo.png'),
  club_ponte_preta: require('./serie-b/club_ponte_preta.png'),
  club_botafogo_sp: require('./serie-b/club_botafogo_sp.png'),
  club_nautico: require('./serie-b/club_nautico.png'),
  club_londrina: require('./serie-b/club_londrina.png'),
  // Série C
  club_serie_c_amazonas: require('./serie-c/club_serie_c_amazonas.png'),
  club_serie_c_anapolis: require('./serie-c/club_serie_c_anapolis.png'),
  club_serie_c_barra: require('./serie-c/club_serie_c_barra.png'),
  club_serie_c_botafogo_pb: require('./serie-c/club_serie_c_botafogo_pb.png'),
  club_serie_c_brusque: require('./serie-c/club_serie_c_brusque.png'),
  club_serie_c_caxias: require('./serie-c/club_serie_c_caxias.png'),
  club_serie_c_confianca: require('./serie-c/club_serie_c_confianca.png'),
  club_serie_c_ferroviaria: require('./serie-c/club_serie_c_ferroviaria.png'),
  club_serie_c_figueirense: require('./serie-c/club_serie_c_figueirense.png'),
  club_serie_c_floresta: require('./serie-c/club_serie_c_floresta.png'),
  club_serie_c_guarani: require('./serie-c/club_serie_c_guarani.png'),
  club_serie_c_inter_limeira: require('./serie-c/club_serie_c_inter_limeira.png'),
  club_serie_c_itabaiana: require('./serie-c/club_serie_c_itabaiana.png'),
  club_serie_c_ituano: require('./serie-c/club_serie_c_ituano.png'),
  club_serie_c_maranhao: require('./serie-c/club_serie_c_maranhao.png'),
  club_serie_c_maringa: require('./serie-c/club_serie_c_maringa.png'),
  club_serie_c_paysandu: require('./serie-c/club_serie_c_paysandu.png'),
  club_serie_c_santa_cruz: require('./serie-c/club_serie_c_santa_cruz.png'),
  club_serie_c_volta_redonda: require('./serie-c/club_serie_c_volta_redonda.png'),
  club_serie_c_ypiranga: require('./serie-c/club_serie_c_ypiranga.png'),
  // Série D
  club_serie_d_tocantinopolis: require('./serie-d/club_serie_d_tocantinopolis.png'),
  club_serie_d_araguaina: require('./serie-d/club_serie_d_araguaina.png'),
  club_serie_d_trem: require('./serie-d/club_serie_d_trem.png'),
  club_serie_d_aguia_de_maraba: require('./serie-d/club_serie_d_aguia_de_maraba.png'),
  club_serie_d_manaus: require('./serie-d/club_serie_d_manaus.png'),
  club_serie_d_manauara: require('./serie-d/club_serie_d_manauara.png'),
  club_serie_d_nacional_am: require('./serie-d/club_serie_d_nacional_am.png'),
  club_serie_d_sao_raimundo_rr: require('./serie-d/club_serie_d_sao_raimundo_rr.png'),
  club_serie_d_porto_velho: require('./serie-d/club_serie_d_porto_velho.png'),
  club_serie_d_galvez: require('./serie-d/club_serie_d_galvez.png'),
  club_serie_d_gremio_atletico_sampaio: require('./serie-d/club_serie_d_gremio_atletico_sampaio.png'),
  club_serie_d_monte_roraima: require('./serie-d/club_serie_d_monte_roraima.png'),
  club_serie_d_guapore: require('./serie-d/club_serie_d_guapore.png'),
  club_serie_d_humaita_ac: require('./serie-d/club_serie_d_humaita_ac.png'),
  club_serie_d_independencia_ac: require('./serie-d/club_serie_d_independencia_ac.png'),
  club_serie_d_oratorio: require('./serie-d/club_serie_d_oratorio.png'),
  club_serie_d_tuna_luso: require('./serie-d/club_serie_d_tuna_luso.png'),
  club_serie_d_abc: require('./serie-d/club_serie_d_abc.png'),
  club_serie_d_america_rn: require('./serie-d/club_serie_d_america_rn.png'),
  club_serie_d_asa: require('./serie-d/club_serie_d_asa.png'),
  club_serie_d_csa: require('./serie-d/club_serie_d_csa.png'),
  club_serie_d_ferroviario_ce: require('./serie-d/club_serie_d_ferroviario_ce.png'),
  club_serie_d_atletico_cearense: require('./serie-d/club_serie_d_atletico_cearense.png'),
  club_serie_d_iguatu: require('./serie-d/club_serie_d_iguatu.png'),
  club_serie_d_maracana: require('./serie-d/club_serie_d_maracana.png'),
  club_serie_d_jacuipense: require('./serie-d/club_serie_d_jacuipense.png'),
  club_serie_d_juazeirense: require('./serie-d/club_serie_d_juazeirense.png'),
  club_serie_d_atletico_de_alagoinhas: require('./serie-d/club_serie_d_atletico_de_alagoinhas.png'),
  club_serie_d_lagarto: require('./serie-d/club_serie_d_lagarto.png'),
  club_serie_d_sergipe: require('./serie-d/club_serie_d_sergipe.png'),
  club_serie_d_sousa: require('./serie-d/club_serie_d_sousa.png'),
  club_serie_d_treze: require('./serie-d/club_serie_d_treze.png'),
  club_serie_d_central_pe: require('./serie-d/club_serie_d_central_pe.png'),
  club_serie_d_retro: require('./serie-d/club_serie_d_retro.png'),
  club_serie_d_iape: require('./serie-d/club_serie_d_iape.png'),
  club_serie_d_moto_club_sao_luis: require('./serie-d/club_serie_d_moto_club_sao_luis.png'),
  club_serie_d_parnahyba: require('./serie-d/club_serie_d_parnahyba.png'),
  club_serie_d_altos: require('./serie-d/club_serie_d_altos.png'),
  club_serie_d_fluminense_pi: require('./serie-d/club_serie_d_fluminense_pi.png'),
  club_serie_d_piaui: require('./serie-d/club_serie_d_piaui.png'),
  club_serie_d_imperatriz: require('./serie-d/club_serie_d_imperatriz.png'),
  club_serie_d_sampaio_correa: require('./serie-d/club_serie_d_sampaio_correa.png'),
  club_serie_d_decisao: require('./serie-d/club_serie_d_decisao.png'),
  club_serie_d_cse: require('./serie-d/club_serie_d_cse.png'),
  club_serie_d_maguary_pe: require('./serie-d/club_serie_d_maguary_pe.png'),
  club_serie_d_porto_ba: require('./serie-d/club_serie_d_porto_ba.png'),
  club_serie_d_serra_branca: require('./serie-d/club_serie_d_serra_branca.png'),
  club_serie_d_laguna_rn: require('./serie-d/club_serie_d_laguna_rn.png'),
  club_serie_d_tirol: require('./serie-d/club_serie_d_tirol.png'),
  club_serie_d_gama: require('./serie-d/club_serie_d_gama.png'),
  club_serie_d_brasiliense: require('./serie-d/club_serie_d_brasiliense.png'),
  club_serie_d_ceilandia: require('./serie-d/club_serie_d_ceilandia.png'),
  club_serie_d_crac: require('./serie-d/club_serie_d_crac.png'),
  club_serie_d_aparecidense: require('./serie-d/club_serie_d_aparecidense.png'),
  club_serie_d_luverdense: require('./serie-d/club_serie_d_luverdense.png'),
  club_serie_d_mixto: require('./serie-d/club_serie_d_mixto.png'),
  club_serie_d_operario_ms: require('./serie-d/club_serie_d_operario_ms.png'),
  club_serie_d_capital_cf: require('./serie-d/club_serie_d_capital_cf.png'),
  club_serie_d_abecat_ouvidorense: require('./serie-d/club_serie_d_abecat_ouvidorense.png'),
  club_serie_d_goiatuba: require('./serie-d/club_serie_d_goiatuba.png'),
  club_serie_d_inhumas: require('./serie-d/club_serie_d_inhumas.png'),
  club_serie_d_ivinhema: require('./serie-d/club_serie_d_ivinhema.png'),
  club_serie_d_uniao_rondonopolis: require('./serie-d/club_serie_d_uniao_rondonopolis.png'),
  club_serie_d_varzea_grande: require('./serie-d/club_serie_d_varzea_grande.png'),
  club_serie_d_rio_branco_es: require('./serie-d/club_serie_d_rio_branco_es.png'),
  club_serie_d_real_noroeste: require('./serie-d/club_serie_d_real_noroeste.png'),
  club_serie_d_vitoria_es: require('./serie-d/club_serie_d_vitoria_es.png'),
  club_serie_d_nova_iguacu: require('./serie-d/club_serie_d_nova_iguacu.png'),
  club_serie_d_portuguesa_rj: require('./serie-d/club_serie_d_portuguesa_rj.png'),
  club_serie_d_america_rj: require('./serie-d/club_serie_d_america_rj.png'),
  club_serie_d_madureira: require('./serie-d/club_serie_d_madureira.png'),
  club_serie_d_marica: require('./serie-d/club_serie_d_marica.png'),
  club_serie_d_portuguesa: require('./serie-d/club_serie_d_portuguesa.png'),
  club_serie_d_agua_santa: require('./serie-d/club_serie_d_agua_santa.png'),
  club_serie_d_velo_clube: require('./serie-d/club_serie_d_velo_clube.png'),
  club_serie_d_noroeste: require('./serie-d/club_serie_d_noroeste.png'),
  club_serie_d_xv_de_piracicaba: require('./serie-d/club_serie_d_xv_de_piracicaba.png'),
  club_serie_d_tombense: require('./serie-d/club_serie_d_tombense.png'),
  club_serie_d_pouso_alegre: require('./serie-d/club_serie_d_pouso_alegre.png'),
  club_serie_d_uberlandia: require('./serie-d/club_serie_d_uberlandia.png'),
  club_serie_d_betim: require('./serie-d/club_serie_d_betim.png'),
  club_serie_d_democrata_gv: require('./serie-d/club_serie_d_democrata_gv.png'),
  club_serie_d_primavera: require('./serie-d/club_serie_d_primavera.png'),
  club_serie_d_sampaio_correa_rj: require('./serie-d/club_serie_d_sampaio_correa_rj.png'),
  club_serie_d_brasil_de_pelotas: require('./serie-d/club_serie_d_brasil_de_pelotas.png'),
  club_serie_d_sao_jose_rs: require('./serie-d/club_serie_d_sao_jose_rs.png'),
  club_serie_d_guarany_de_bage: require('./serie-d/club_serie_d_guarany_de_bage.png'),
  club_serie_d_sao_luiz: require('./serie-d/club_serie_d_sao_luiz.png'),
  club_serie_d_joinville: require('./serie-d/club_serie_d_joinville.png'),
  club_serie_d_marcilio_dias: require('./serie-d/club_serie_d_marcilio_dias.png'),
  club_serie_d_blumenau: require('./serie-d/club_serie_d_blumenau.png'),
  club_serie_d_sao_joseense: require('./serie-d/club_serie_d_sao_joseense.png'),
  club_serie_d_cianorte: require('./serie-d/club_serie_d_cianorte.png'),
  club_serie_d_fc_cascavel: require('./serie-d/club_serie_d_fc_cascavel.png'),
  club_serie_d_azuriz: require('./serie-d/club_serie_d_azuriz.png'),
  club_serie_d_santa_catarina: require('./serie-d/club_serie_d_santa_catarina.png'),
  // Argentina — Primera División (football-logos.cc)
  club_boca_juniors: require('./argentina/club_boca_juniors.png'),
  club_racing_club: require('./argentina/club_racing_club.png'),
  club_lanus: require('./argentina/club_lanus.png'),
  club_river_plate: require('./argentina/club_river_plate.png'),
  club_independiente: require('./argentina/club_independiente.png'),
  club_san_lorenzo: require('./argentina/club_san_lorenzo.png'),
  club_estudiantes: require('./argentina/club_estudiantes.png'),
  club_velez_sarsfield: require('./argentina/club_velez_sarsfield.png'),
  club_rosario_central: require('./argentina/club_rosario_central.png'),
  club_newells_old_boys: require('./argentina/club_newells_old_boys.png'),
  club_talleres: require('./argentina/club_talleres.png'),
  club_argentinos_juniors: require('./argentina/club_argentinos_juniors.png'),
  club_defensa_y_justicia: require('./argentina/club_defensa_y_justicia.png'),
  club_huracan: require('./argentina/club_huracan.png'),
  club_gimnasia_lp: require('./argentina/club_gimnasia_lp.png'),
  club_banfield: require('./argentina/club_banfield.png'),
  club_tigre: require('./argentina/club_tigre.png'),
  club_central_cordoba: require('./argentina/club_central_cordoba.png'),
  club_platense: require('./argentina/club_platense.png'),
  club_godoy_cruz: require('./argentina/club_godoy_cruz.png'),
  // Inglaterra — Premier League (football-logos.cc)
  club_man_city: require('./inglaterra/club_man_city.png'),
  club_liverpool: require('./inglaterra/club_liverpool.png'),
  club_chelsea: require('./inglaterra/club_chelsea.png'),
  club_arsenal: require('./inglaterra/club_arsenal.png'),
  club_man_united: require('./inglaterra/club_man_united.png'),
  club_tottenham: require('./inglaterra/club_tottenham.png'),
  club_newcastle: require('./inglaterra/club_newcastle.png'),
  club_aston_villa: require('./inglaterra/club_aston_villa.png'),
  club_brighton: require('./inglaterra/club_brighton.png'),
  club_nottingham_forest: require('./inglaterra/club_nottingham_forest.png'),
  club_crystal_palace: require('./inglaterra/club_crystal_palace.png'),
  club_fulham: require('./inglaterra/club_fulham.png'),
  club_bournemouth: require('./inglaterra/club_bournemouth.png'),
  club_everton: require('./inglaterra/club_everton.png'),
  club_west_ham: require('./inglaterra/club_west_ham.png'),
  club_burnley: require('./inglaterra/club_burnley.png'),
  club_brentford: require('./inglaterra/club_brentford.png'),
  club_wolves: require('./inglaterra/club_wolves.png'),
  club_leeds: require('./inglaterra/club_leeds.png'),
  club_sunderland: require('./inglaterra/club_sunderland.png'),
  // Inglaterra — Championship (football-logos.cc)
  club_leicester: require('./inglaterra/club_leicester.png'),
  club_southampton: require('./inglaterra/club_southampton.png'),
  club_ipswich: require('./inglaterra/club_ipswich.png'),
  club_sheffield_united: require('./inglaterra/club_sheffield_united.png'),
  club_coventry: require('./inglaterra/club_coventry.png'),
  club_stoke: require('./inglaterra/club_stoke.png'),
  club_norwich: require('./inglaterra/club_norwich.png'),
  club_middlesbrough: require('./inglaterra/club_middlesbrough.png'),
  club_watford: require('./inglaterra/club_watford.png'),
  club_derby: require('./inglaterra/club_derby.png'),
  club_swansea: require('./inglaterra/club_swansea.png'),
  club_blackburn: require('./inglaterra/club_blackburn.png'),
  club_millwall: require('./inglaterra/club_millwall.png'),
  club_wrexham: require('./inglaterra/club_wrexham.png'),
  club_qpr: require('./inglaterra/club_qpr.png'),
  club_bristol_city: require('./inglaterra/club_bristol_city.png'),
  club_portsmouth: require('./inglaterra/club_portsmouth.png'),
  club_oxford: require('./inglaterra/club_oxford.png'),
  club_west_brom: require('./inglaterra/club_west_brom.png'),
  club_hull: require('./inglaterra/club_hull.png'),
  club_preston: require('./inglaterra/club_preston.png'),
  club_birmingham: require('./inglaterra/club_birmingham.png'),
  club_sheffield_wednesday: require('./inglaterra/club_sheffield_wednesday.png'),
  club_charlton: require('./inglaterra/club_charlton.png'),
};

// Logo por divisão (cada série tem o seu emblema).
export const LOGO_SERIE_A: ImageSourcePropType = require('../brasileiraoA.png');
export const LOGO_SERIE_B: ImageSourcePropType = require('../brasileiraoB.png');
export const LOGO_SERIE_C: ImageSourcePropType = require('../brasileiraoC.png');
export const LOGO_SERIE_D: ImageSourcePropType = require('../brasileiraoD.png');
/** Logo oficial da Copa do Brasil. */
export const LOGO_COPA: ImageSourcePropType = require('../copaDoBrasil.png');

// Emblemas das ligas internacionais (football-logos.cc).
export const LOGO_PREMIER: ImageSourcePropType = require('../premierLeague.png');
export const LOGO_CHAMPIONSHIP: ImageSourcePropType = require('../championship.png');
export const LOGO_PRIMERA: ImageSourcePropType = require('../primeraArgentina.png');

const LOGO_POR_DIVISAO: Record<string, ImageSourcePropType> = {
  'Série A': LOGO_SERIE_A,
  'Série B': LOGO_SERIE_B,
  'Série C': LOGO_SERIE_C,
  'Série D': LOGO_SERIE_D,
  'Premier League': LOGO_PREMIER,
  Championship: LOGO_CHAMPIONSHIP,
  'Primera División': LOGO_PRIMERA,
};

/** Emblema da divisão (cai para a logo da Série A se desconhecida). */
export function logoDaDivisao(divisao?: string): ImageSourcePropType {
  return (divisao && LOGO_POR_DIVISAO[divisao]) || LOGO_SERIE_A;
}

export function escudoDoTime(clubeId: string): ImageSourcePropType | undefined {
  return ESCUDOS[clubeId];
}
